apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  # labels are key-value pairs that are used to organize and select groups of objects. 
  # They can be used to identify attributes of objects that are meaningful and relevant to users, 
  # but do not directly imply semantics to the core system.
  labels:
    key-label1: value-label1
    key-label2: value-label2
  # Annotations are key-value pairs that can be used by external tooling to store and retrieve arbitrary metadata about this object.
  # Annotations are not queryable and should be preserved when modifying objects.
  annotations:
    key-annotation1: value-annotation1
    key-annotation2: value-annotation2
spec:
  containers:
    - name: container-name
      image: image-name
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi