apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replication-controller
spec:
  replicas: 2
  selector:
    label-key1: label-value1
  template:
    metadata:
      name: example-pod
      labels:
        label-key1: label-value1
    spec:
      containers:
        - name: example-container
          image: example-image:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1